baseurl      = "zachary-m-johnson"
title        = "My Blog"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

[author]
  name = "Zachary M Johnson"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "Software Consultant & Developer"

  # Enable theme toggle
  # 
  # This options enables the theme toggle for the theme. 
  # Per default, this option is off. 
  # The theme is respecting the prefers-color-scheme of the operating systeme. 
  # With this option on, the page user is able to set the scheme he wants. 
  enableThemeToggle = true

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]

  [params.footer]
    trademark = true
    rss = true
    copyright = true
    author = true

    topText = []
    bottomText = [
      "Powered by <a href=\"http://gohugo.io\">Hugo</a>",
      "Made with &#10084; by <a href=\"https://github.com/rhazdon\">Djordje Atlialp</a>"
    ]

  [[params.social]]
    name = "email"
    url  = "mailto:zachary.moritz.johnson@gmail.com"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/zachary-m-johnson"

  [[params.social]]
    name = "github"
    url  = "https://github.com/zmjohnso"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Zachary M Johnson"
    subtitle = "Software Consultant & Developer"
    keywords = ""
    copyright = '<a href="https://opensource.org/licenses/MIT" target="_blank" rel="noopener">MIT License</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "$ cd /home/"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about/"
    
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "posts/"